version: '3.9'
services:
  app:
    build: ./cargar-bajar
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - API_CARGAR=${API_CARGAR}
      - API_BAJAR=${API_BAJAR}
    depends_on:
      - api
    restart: always
    networks:
      - internal

  api:
    build: ./backend
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/${DB_NAME}
      - PORT=${API_PORT}
      - DB_NAME=${DB_NAME}
      - DB_COLLECTION=${DB_COLLECTION}
    restart: always
    user: "nobody"
    networks:
      - internal

  mongo:
    build: ./mongo
    environment:
      - DB_NAME=${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    user: "mongodb"
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  mongo-data:
