version: '3.9'
services:
  app:
    build: ./cargar-bajar
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - API_CARGAR=${API_CARGAR}
      - API_BAJAR=${API_BAJAR}
    depends_on:
      - api

  api:
    build: ./backend
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:${DB_PORT}/${DB_NAME}
      - PORT=${API_PORT}
      - DB_NAME=${DB_NAME}
      - DB_COLLECTION=${DB_COLLECTION}

  mongo:
    build: ./mongo
    environment:
      - DB_NAME=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: