FROM node:14 as build-stage
WORKDIR /app
COPY package*.json ./

ENV NODE_TLS_REJECT_UNAUTHORIZED=0

RUN npm install
COPY . .
RUN npm run build --prod

FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist/* /usr/share/nginx/html

COPY localhost.crt /etc/nginx/ssl/localhost.crt
COPY localhost.key /etc/nginx/ssl/localhost.key

COPY nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]